# Auth server pool
auth:
  - limbo
  - limbo-1

# Pool of servers to connect after authorization
next:
  - instance

# Server info update period in seconds
update_period: 30

# Player checker period
checker_period: 5000

# Non-authorized player lifetime before kick in seconds
kick_period: 30

# Session expire seconds
expire: 7200

# Database (type memo by default)
# db:
#  type: "jdbc"
#  url: "jdbc:postgresql://192.168.1.48/minecraft"
#  user: "minecraft"
#  pass: "heresthemftea"

# Balancers (me.theseems.tauth.balancers.SimpleBalancer by default)
# auth_balancer:
#  class: me.theseems.tauth.balancers.AsyncBalancer
#  settings:
# Delay in milliseconds
#    - 10000
# next_balancer:
#  class: me.theseems.tauth.balancers.SimpleBalancer

# You can change hashing algorithm here (me.theseems.tauth.hashers.SHA512AuthHasher by default)
# hasher:
#  class: me.theseems.tauth.hashers.SHA512AuthHasher

# Localization
messages:
  login:
    usage: '§eUsage§7: §e/login §7<pass>'
    titles:
      UNREGISTERED:
        title: §7Please, register
        subtitle: §e/register §7<pass> <pass>
        fade_in: 10
        fade_out: 10
        stay: 30
      EXPIRED:
        title: §7Please, login
        subtitle: §e/login §7<pass>
        fade_in: 10
        fade_out: 10
        stay: 30
      FORBIDDEN:
        title: §cWrong password!
        subtitle: ''
        fade_in: 10
        fade_out: 10
        stay: 30
      OK:
        title: §aYou are logged in
        subtitle: ''
        fade_in: 10
        fade_out: 10
        stay: 30
  register:
    titles:
      OK:
        title: §aYou are registered
        subtitle: ''
        fade_in: 10
        fade_out: 10
        stay: 30
    usage: "§eUsage§7 §e/register §7<pass> <repeat-pass>"
    no_match: "§7Passwords §cdont match"
  kick:
    timed_out: §c§lYou have run out of time to log in