# Auth server pool
auth:
  - limbo
  - limbo-1

# Pool of servers to connect after authorization
next:
  - instance

# Server info update period in seconds
update_period: 30

# Player checker period
checker_period: 5000

# Non-authorized player lifetime before kick in seconds
kick_period: 30

# Session expire seconds
expire: 7200

# Debug information
# debug: false

# Database (type memo by default)
# db:
#  type: "jdbc"
#  url: "jdbc:postgresql://192.168.1.48/minecraft"
#  user: "minecraft"
#  pass: "heresthemftea"

# Balancers (me.theseems.tauth.balancers.SimpleBalancer by default)
# auth_balancer:
#  class: me.theseems.tauth.balancers.AsyncBalancer
#  settings:
# Delay in milliseconds
#    - 10000
# next_balancer:
#  class: me.theseems.tauth.balancers.SimpleBalancer

# You can change hashing algorithm here (me.theseems.tauth.hashers.SHA512AuthHasher by default)
# hasher:
#  class: me.theseems.tauth.hashers.SHA512AuthHasher